name: E2E Junit Report
on:
  workflow_run:
    workflows: [ "End-to-end tests" ]
    types: [ completed ]

permissions:
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          merge-multiple: true
          pattern: e2e-junit-*
          path: '.testresults/e2e'
          run-id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@65fe03598d8d251738592a497a9e8547a5c48eaa # v5.6.0
        if: always()
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '.testresults/e2e/*.xml'
          comment: true
          skip_annotations: true
          include_passed: true